import './data.css'
export default function Home() {
  return (
    <>
        <div className='data'>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at faucibus massa, ac elementum diam. Nunc pulvinar lectus in elit venenatis, at lacinia metus imperdiet. Sed nibh felis, sodales ut elementum et, tempus vitae elit. Curabitur dignissim vulputate turpis ultricies mattis. Phasellus rhoncus, magna id dictum elementum, lacus lorem porta purus, at mattis nulla ante dictum ante. In vitae urna tellus. Nulla aliquam, odio nec placerat semper, ex est blandit lectus, at blandit arcu ante ut est. Mauris ultricies venenatis dignissim. Etiam iaculis pretium urna nec dapibus. Nam in est eget magna facilisis gravida at non dui.
        </div> 
        <div>
        Aliquam faucibus enim in dui euismod eleifend nec vitae ex. Morbi auctor porta malesuada. Pellentesque a sodales nulla. Vestibulum a facilisis lacus. Donec felis purus, varius ut metus nec, dapibus luctus tellus. Sed sit amet pretium lacus. Nunc ut egestas ligula, in vestibulum metus. Curabitur dictum felis a posuere cursus. Nam nisl nulla, vehicula sed luctus a, sollicitudin at felis. Quisque a facilisis erat.
        
        Proin imperdiet accumsan risus, vel iaculis quam. Phasellus quis purus at lacus venenatis congue. Donec tincidunt purus sit amet viverra consectetur. Aenean scelerisque a lacus at porttitor. Mauris malesuada in lorem et sagittis. Aenean id bibendum orci. Vivamus fringilla imperdiet metus sit amet semper. Pellentesque a augue lectus. Vivamus lobortis erat non maximus mollis. Etiam feugiat rhoncus pharetra. Nam tincidunt ipsum vitae ligula commodo, ut euismod nulla rhoncus. Nunc ultrices urna vel nulla luctus, sit amet posuere dui imperdiet. Suspendisse hendrerit magna convallis velit cursus, vel bibendum augue pharetra.
        
        Quisque commodo vel erat eu cursus. Phasellus eget libero nec lacus laoreet interdum vel id eros. Proin facilisis, urna eget ultrices venenatis, quam purus egestas massa, et dapibus felis nulla a purus. Nullam commodo placerat tellus ut consequat. Sed egestas odio massa, a ultricies orci accumsan eget. Maecenas vulputate eget ipsum eu maximus. Etiam varius nibh sit amet ante efficitur mollis. Sed at turpis at enim fringilla volutpat pretium sit amet nulla. Vestibulum in nunc laoreet, cursus eros nec, auctor lacus. Donec nec mattis justo. Cras non tempus enim. Etiam lacinia sit amet orci et rhoncus.
        
        Suspendisse sit amet tempus mauris. Donec nunc tellus, tincidunt finibus fermentum a, maximus sed purus. Donec ultrices id eros eget rhoncus. Nullam mauris turpis, dictum eget ipsum ut, ornare maximus odio. Praesent eget libero quis diam interdum fermentum sit amet sit amet libero. Vivamus commodo auctor mi, vel laoreet lorem convallis et. Aliquam imperdiet lorem ante, sed cursus purus aliquet sit amet. Integer vulputate, odio eu aliquam aliquet, neque magna dapibus dui, id pellentesque nulla dolor in sapien. Proin bibendum rutrum metus sed rutrum. Mauris vestibulum id massa vel tempus. Cras velit quam, dictum ut dui lobortis, aliquet feugiat dolor. Proin est sem, porta quis ultrices sed, lacinia in mi. Aliquam erat volutpat.
        </div> <div>
        Integer luctus cursus sapien, vel porttitor ligula porta faucibus. Vestibulum massa arcu, sollicitudin non nibh ac, fermentum faucibus nunc. Maecenas aliquet interdum scelerisque. Morbi sed semper libero, id ullamcorper tellus. Nam sollicitudin velit nibh, ac lobortis dolor volutpat non. Proin rutrum erat id ultrices imperdiet. Aliquam consectetur, lorem non posuere porta, diam dolor posuere turpis, in aliquam enim sapien id neque. Nam nisi quam, hendrerit nec quam ac, blandit fermentum sem. Nullam dignissim sem non lacus scelerisque, sed consequat sapien elementum. Ut in tempus mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium molestie leo, ac varius dolor. Ut pharetra lacus lacus, et imperdiet ante vehicula et. Phasellus tempus justo a diam rhoncus convallis. Aenean fermentum euismod sapien, vel pretium felis dictum auctor. Sed sed odio sed metus hendrerit molestie.
        
        Fusce pharetra pellentesque ex non pretium. Etiam vulputate velit viverra turpis semper, in lacinia justo viverra. Aliquam malesuada porta dui, at ornare nunc pretium in. Vestibulum at fringilla quam. Donec vel libero mauris. Mauris dolor purus, rhoncus vel massa et, efficitur sagittis eros. Fusce id vehicula enim, ac lacinia tortor. Praesent porttitor nunc quis lacinia molestie. Duis tortor massa, tempus cursus enim at, suscipit bibendum justo. Nulla suscipit fermentum enim feugiat congue. Nulla pretium tortor a justo suscipit vehicula. Maecenas interdum blandit nunc at lobortis.
        
        Vivamus malesuada massa sed tellus hendrerit vehicula. Sed vitae metus eleifend, euismod dolor eu, auctor nibh. Integer dignissim ante at tortor vehicula lobortis. Fusce iaculis quam nec efficitur luctus. Donec efficitur est neque, non placerat sapien sagittis at. Ut a tincidunt arcu. Sed sit amet metus a turpis tincidunt aliquet. Maecenas blandit porttitor felis, bibendum pharetra dolor dignissim in. Donec sodales quam eu sodales suscipit. Praesent metus quam, ullamcorper eget commodo at, lobortis ut ligula.</div>
        </div>
        <div className='data-2'>
            What is Lorem Ipsum?
                 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

                Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).


            Where does it come from?
            Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

            The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

            Where can I get some?
            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
        </div>
    </>
  )
}

